### ISSUE TITLE
Path variables to execute

### ISSUE THREAD

**Issue by happyalexkg** [adedov/libiqxmlrpc#2]
Hello
I need to pass some arguments to .execute
`#include <iostream>
#include <libiqxmlrpc/libiqxmlrpc.h>
#include <libiqxmlrpc/http_client.h>

int main()
{
  using namespace iqxmlrpc;

//Client<Http_client_connection> client(iqnet::Inet_addr(3344));
Client<Http_client_connection> client( iqnet::Inet_addr("176.126.167.203", 2633), "/RPC2" );

  Param_list pl;
  pl.push_back(Struct());
  pl[0].insert("var1","username:passsword");
  pl[0].insert("var2",-1);

  Response r = client.execute("one.user.info", pl);
  std::cout << r.value()["var1"].get_string() << std::endl;
}
`

but i;m getting error
"terminate called after throwing an instance of 'iqxmlrpc::Exception'
  what():  Parameter that is supposed to be a string is not
"

seems that RPC2 getting array. not a string :(

**Comment by adedov** [comment]
Hi!

Thank you for reporting!

Can you provide server code? I suppose that the problem can be not in /RPC2 but var2 to be int.

**Comment by happyalexkg** [comment]
Hello
I have "ABYSS Web Server for XML-RPC For C/C++ version 1.40.0" as server
for example:
when i tried xmlrpc-c:
I did:
myClient.call(serverUrl, methodName, "si", &result, "username:password",-1);

As far as you can see - i'm can tell to procedure - type of value:
s - string
i - interger

for method one.user.info server expects:
one value string and another is - int

It will be cool if it possible to tell your execute type of value :)

sorry for my english :)

**Comment by adedov** [comment]
Well, I think I see your issue. Those tow examples you have provided are far from equivalent:
1) In iqxmlrpc version you call a method with one parameter - struct and put two fields in it: var1, var2
2) In xmlrpc-c version you call a method with two parameters - string and int.

If you want equivalent behaviour in iqxmlrpc, use following sample:
```
Param_list pl;
pl.push_back("username:password");
pl.push_back(-1);
Response r = client.execute("one.user.info", pl);
```

**Comment by happyalexkg** [comment]
Hm, ok i will try and will back to you :)
thx

**Comment by happyalexkg** [comment]
forgot to menstion
seems that server return array :)

**Comment by adedov** [comment]
May be following snippet would work:
`r.value().the_array()`

Anyways, the dump from your response does not look like XML-RPC. Can you provide full HTTP response?

**Comment by adedov** [comment]
No reply from reporter.
