### ISSUE TITLE
sysinc.h WIN32 Macro is Undefined

### ISSUE THREAD

**Issue by Snork2** [adedov/libiqxmlrpc#3]
in `sysinc.h` file on 12 line there is:

```
#ifdef WIN32
  #define BOOST_ALL_NO_LIB

// more code omitted

#endif
```

This line fails compilation on windows, when this header included in project, which is using library. The correct macro should be `_WIN32`. It is defined by MSVC and MINGW.

I wanted to add a pull request, but it seems, that `WIN32` macro is heavily used by CMAKE, so i decided to make a simple issue.

**Comment by dontsovcmc** [comment]
WIN32 is right macro. (it also be presented in another 11 files)
Describe you build steps, please.
see: https://github.com/adedov/libiqxmlrpc/wiki/Building

**Comment by Snork2** [comment]
No, the library build is fine. It is complicated under windows, but no library source edit was required. I'm talking about usage of compiled library in another project. In particular, it was the first client example from wiki:
```
    #include <iostream>
    #include <libiqxmlrpc/libiqxmlrpc.h>
    #include <libiqxmlrpc/client.h>
    #include <libiqxmlrpc/http_client.h>
    
    int main()
    {
      using namespace iqxmlrpc;
    
      // 1: Create a client object
      Client<Http_client_connection> client(iqnet::Inet_addr(3344));
    
      // 2: Fill method parameters
      Param_list pl;
      pl.push_back(Struct());
      pl[0].insert("var1", 1);
      pl[0].insert("var2", "value");
    
      // 3: Call a remote method
      Response r = client.execute("echo", pl);
    
      // 4: Process method output
      assert(r.value()["var1"].get_int() == 1);
      assert(r.value()["var2"].get_string() == "value");
    }
```

It seems that some of the library headers included `sysinc.h`. In this file a check for windows platform (`#ifdef WIN32`) failed and compiler said, that it is unable to find `unistd.h`. After I edited this header and replaced `WIN32` with `_WIN32`, without touching already built library binaries, everything works as expected.

P.S. I'm using Microsoft Visual Studio 2013 community edition.

**Comment by dontsovcmc** [comment]
I guess you don't use CMAKE for create Visual Studio project file. That's why you should define WIN32 manually. Open project property page - Configuration Properties - C/C++ - Preprocessor - Preprocessor Definitions
add WIN32
do this for all your build types (Debug, Release and etc)

**Comment by Snork2** [comment]
Yes, my own project is not using CMAKE.

So, its is designed behavior and defining of WIN32 macro is necessary? Okay, thank you. I'm closing issue then
